services:
  dns-updater:
    image: python:latest
    restart: always
    volumes:
      - /home/pi/google-dns-updater:/updater
    command: "/bin/sh -c 'cd /updater; ./initiate.sh'"
    environment:
      - LOKI_URL=http://rednodepi.local.net:3100/loki/api/v1/push
      - LOG_LEVEL=INFO
